spring:
  flyway:
    schemas: geschaeft
    create-schemas: true
    url: jdbc:postgresql://localhost:5432/
    user: propra2
    password: propra2
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: propra2
    password: propra2