spring:
  flyway:
    schemas: geschaeft
    create-schemas: true
    url: jdbc:postgres://localhost:5432/
    user: propra2
    password: propra2
  datasource:
    url: jdbc:postgres://localhost:5432/geschaeft
    username: propra2
    password: propra2